apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sample-app
  namespace: default
spec:
  interval: 1m0s
  url: https://github.com/gaurav2203/advanced_k8s
  ref:
    branch: main
